# Generated by Django 4.1.7 on 2023-03-16 05:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weathertrackerapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
